### ISSUE TITLE
TFS 2017

### ISSUE THREAD

**Issue by HippyCraig** [Vinzz/TFSAdminTool#2]
TFS 2017 just RTM a few days ago, sometime late last week.  Will this tool be updated to use that newer model?  I am going to me installing 2017 in our prod environment it would be nice if this worked there too.  Especially since your the only one that fixed the SP account issues

**Comment by Vinzz** [comment]
Hi, I will, update this tool for sure, as soon as I have a TFS 2017 up and running, sometime in december for sure.
But it might work already? Did you conduct any test?

**Comment by HippyCraig** [comment]
I am in the process of updating our TFS 2013.4 to 2017 now, as soon as the upgrade is complete I will test the older client, I can also test the newer client for you when you have something to review.  We use all of TFS.  Sharepoint, SSRS, and TFS, its also load balanced through netscaler so I can test the connections through that as well.

**Comment by HippyCraig** [comment]
I have tried to test this with TFS 2017, I am getting errors that Sharepoint and reporting can't connect.  Not sure if its an issue with having VS2013, VS2015, and VS2017 installed on the same machine or not

**Comment by HippyCraig** [comment]
I haven't heard back is this something that you are looking at?

**Comment by Vinzz** [comment]
Hi, I'm still in the migration process toward TFS 2017, so no progress on this for the moment

**Comment by HippyCraig** [comment]
ok I will check back in, thanks for getting back to me.  FYI i now have TFS2017 up and running so I can be a tester for you if needed.

**Comment by Vinzz** [comment]
Hi HippyCraig, I just made some tests against a TFS 2017 (SQL 2016 and SharePoint 2016, though) and the tool do work OK.
Are you using a different SSRS or SP version?

**Comment by HippyCraig** [comment]
I am using TFS2017 Update 1, with SSRS 2014, and SharePoint Foundation 2013 with the latest CU

**Comment by HippyCraig** [comment]
I will be doing more testing over the next week, I think we may have some issues with network connections in the new data center that is hosting 2017.  I will post my findings, thank you for the update.

**Comment by HippyCraig** [comment]
So was able to give it a try on a full install. It appears to complete but I get an error on screen and I have attached the logs.  Again when adding and refreshing it shows completed, but there is a log entry.  When deleting I see that it completes but again displays an error.

**Comment by HippyCraig** [comment]
Sorry this looks to be just from missing email settings.  My apologizes, it appears to be working fine.

**Comment by Vinzz** [comment]
Got it, that's a too strict email validation issue, I will make a fix tomorrow

**Comment by HippyCraig** [comment]
Awesome

**Comment by Vinzz** [comment]
Hi, @HippyCraig , this should fix your issue:
https://github.com/Vinzz/TFSAdminTool/releases/tag/v2.6

~~Note: I just discovered that the uninstaller left the files behind, I'll fix that soon~~ **Fixed**
